config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get "dashboard", to: "dashboards#dashboard", as: 'dashboard'
  get 'profile/:id', to: 'pages#profile', as: :profile
  post 'bookings/:id/handle_booking', to: "bookings#handle_booking", as: :handle_booking
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :events do
    resources :bookings, only: [ :create, :destroy]
  end

  resources :users do
    resources :reviews, only: [ :create, :destroy ]
  end
end

app/views/pages/_about.html.erb
<div class="about-card">
<div class="col-6 p-0 offset-3">
  <div class="about-card-details">
    <h1 class="h1-profile-sm">Details</h1>
    <div class="d-flex justify-content-around">
      <div class="details-left">
        <p><i class="fas fa-map-marker-alt"></i><span class="details-tag">Location: </span><%=@user.city%></p>
        <p><i class="fas fa-globe-europe"></i>Language: <%=@user.language %></p>
      </div>
      <div class="details-right">
        <p><i class="fas fa-male"></i>Height: <%=@user.height %></p>
        <p><i class="fas fa-history"></i>Age: <%=@user.age %></p>
      </div>
    </div>
  </div>
  <div class="about-card-details">
    <h1 class="h1-profile-sm">Fun Facts</h1>
    <div class="d-flex justify-content-around">
      <div class="details-left">
        <p><i class="fas fa-dumbbell"></i>Strengths: <%=@user.strength %></p>
        <p><i class="fas fa-magic"></i>Hidden Talent: <%=@user.hidden_talent%></p>
      </div>
      <div class="details-right">
        <p><i class="fas fa-comment"></i>Talkativeness: <%=@user.talkativeness %> / 5</p>
        <p><i class="fas fa-laugh-beam"></i>Funniness: <%=@user.funniness%> / 5</p>
      </div>
    </div>
</div>
<div class="profile-card-actions">
    <%=link_to edit_user_path(@user) do %>
      Edit profile <i class="fa fa-pencil"></i>
    <% end %>
</div>

</div>
</div>

app/views/pages/_events-trending.html.erb
<div class="row">
  <% @events_first.each do |event| %>
    <div class="col-6 col-mb-4 col-lg-4 mb-4">
      <%= link_to event_path(event) do  %>
        <div class="profile-card">
          <% if event.event_image.present? %>
            <div class="profile-card-image" style="background-image: url(<%= event.event_image %>)"></div>
          <% else %>
            <div class="profile-card-image" style="background-image: url(<%=event.event_category.default_image %>)"> </div>
          <% end %>
        <div class="profile-card-content">
          <div class="profile-card-title">
            <p class="category-tag"><%= event.event_category.name %></p>
            <h4><%= event.name %></h4>
            <p class="crop-description"><%= event.event_description %></p>
          </div>
          <div class="profile-card-actions">
            <%= link_to 'See more', event_path(event)%>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/pages/_journey.html.erb
 <div class="container">
   <div class="row">
    <div class="col-12 col-mb-6 col-lg-6 mt-3 offset-3">
     <div class="card-event-company-connection mb-1 mt-1 start">
      <%= image_tag "logo_green.png", class: "logo-journey-start" %>
    </div>
    <% @user.events.order(:date).each do |event| %>
         <div class="card-event-company-connection mb-1 mt-1">
        </div>
        <div class="card-event-company">
          <div class="d-flex">
             <%# image_tag event.event_image, class: "avatar-large mr-2" %>
            <div class="card-event-company-content">
              <p><span class="p-question">Event? </span><%= event.name %></p>
              <p><span class="p-question">Host? </span><%= @user.first_name %></p>
              <p><span class="p-question">When? </span><%= event.date %></p>

              <% companion = event.approved_companion %>

              <% if companion %>
                <p><span class="p-question">Companions? </span><%= @user.first_name%> & <%= companion.first_name %></p>
              <% else %>
                <p><span class="p-question">Companions? </span><%= @user.first_name%> & TBD ☺️ </p>
              <% end %>


            </div>
          </div>
          <div class="card-event-company-actions">
            <%= link_to event_path(event) do %>
              <i class="far fa-calendar-check"></i>
            <% end %>
          </div>
        </div>
      <% end %>
      <!-- Would need a joined table to sort for date -->
     <% @user.bookings.order(:created_at).each do |booking| %>
        <div class="card-event-company-connection mb-1 mt-1">
        </div>
        <div class="card-event-request">
          <div class="d-flex">
            <div class="card-event-ahead-content">
              <p><span class="p-question">Event? </span><%= booking.event.name %></p>
              <p><span class="p-question">Host? </span><%= booking.event.user.first_name %></p>
              <p><span class="p-question">When? </span><%= booking.event.date %></p>
              <p><span class="p-question">Companions? </span><%= booking.event.user.first_name %> & <%= @user.first_name %></p>
            </div>
          </div>
          <div class="card-event-company-actions journey">
            <%= link_to event_path(booking.event) do %>
              <i class="far fa-calendar-check"></i>
            <% end %>
          </div>
        </div>
    <% end %>
    </div>
  </div>
</div>

app/views/pages/_reviews.html.erb
 <div class="col-6 p-0 offset-3">

  <% if current_user.id != @user.id %>
    <h1 class="h1-profile mb-4">Would you like to leave a review?</h1>
    <%= simple_form_for [@user, @review] do |f| %>
      <%= f.input :description, label: "What do you think about #{@user.first_name} and the event?", class: "review-label" %>
      <%= f.input :rating, label: 'How many stars would you give?', class: "review-label" %>
      <%= f.submit "Leave a review", class: "btn custom" %>
    <% end %>
  <% end %>

   <h1 class="h1-profile mt-4 mb-4">See what other companions said about me</h1>
  <div class="row">
    <% @user.received_reviews.each do |review| %>
    <div class="col-12 col-mb-12 col-lg-12 mb-4">
      <div class="card-event-request">
        <div class="d-flex">
            <%= cl_image_tag review.reviewer.profile_image, class: "avatar-large mr-3" %>
            <div class="card-event-request-content">
              <p id="p-reviewer"><%= review.reviewer.first_name %> <%= review.reviewer.last_name %></p>
              <small><span class="p-stars"><% review.rating.times do %>
                <i class="fas fa-star mine"></i>
              <% end %></span></small>
              <p><span class="review-description"><%= review.description %></span></p>
            </div>
          </div>
      </div>
    </div>
      <% end %>
  </div>


</div>

app/views/pages/home.html.erb
<div class="banner-home">
  <div class="banner-text-home">Find good company for your adventures</div>

</div>

<div class="container margin-top-negative">
  <div class="row">
    <div class="col-12 col-mb-6 col-lg-6">
      <div class="search-show-card">
        <h1>What are you looking for?</h1>

        <%= form_tag events_path, method: :get do %>
        <div class="form-group">
          <%= text_field_tag :city,
          params[:city],
          class: "form-control",
            id: "location-input",
            required: true,
            placeholder: "Where?"

            %>
          </div>
          <div class="form-group">
            <%= date_field_tag :date_range,
            params[:date_range],
            class: "form-control",
            class: "datepicker",
              required: true,
              placeholder: "Date range?"
              %>
            </div>


              <div class="form-group">
                <label class="control-label check_boxes optional">What are you up for?</label>
                <input type="hidden" name="post[category_ids][]" value="">
                <div class="category-choices">
                  <% EventCategory.all.each do |category| %>
                  <input type="checkbox" class="d-none" autocomplete="off" value="<%= category.id %>" name="post[category_ids][]" id="post_category_ids_<%= category.id %>">
                  <label class="category-choice" for="post_category_ids_<%= category.id %>">
                    <%= category.name %>
                  </label>
                  <% end %>
                </div>
              </div>

              <%= submit_tag "Submit", class: "btn custom" %>
              <% end %>

            </div>
          </div>
        </div>


      <div class="container mt-5">
      <h3>Trending events close to you..</h3>
      </div>
        <%= render 'events-trending'%>


      </div>
<%= content_for(:after_js) do %>
  <%= javascript_pack_tag "resetcheckboxes" %>
<% end %>


  <!--         <div class="col-6 col-mb-4 col-lg-4 mb-4">
              <div class="flat-card">
                <div class="flat-card-image" style="background-image: url('https://images.unsplash.com/photo-1525373612132-b3e820b87cea?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60')"></div>
                <div class="flat-card-content"> -->
                  <!-- if statement & checkbox image -->
                  <!-- <div class="flat-card-title">
                    <h4>Event Name</h4>
                  </div>
                  <div class="flat-card-actions">
                    <p>Link to Event Show Page</p>
                    <i class="fa fa-pencil"></i>
                    <i class="fa fa-trash-o"></i>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-6 col-mb-4 col-lg-4 mb-4">
              <div class="flat-card">
                <div class="flat-card-image" style="background-image: url('https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/tanbackground-1553877785.jpg?resize=480:*')"></div>
                <div class="flat-card-content"> -->
                  <!-- if statement & checkbox image -->
                 <!--  <div class="flat-card-title">
                    <h4>Event Name</h4>
                  </div>
                  <div class="flat-card-actions">
                    <p>Link to Event Show Page</p>
                    <i class="fa fa-pencil"></i>
                    <i class="fa fa-trash-o"></i>
                  </div>
                </div>
              </div>
            </div> -->

app/views/pages/profile.html.erb
<div class="profile-header">
    <%= cl_image_tag @user.profile_image, class: "avatar-profile mr-2" %>
    <h1 class="h1-profile-wm"><%= @user.first_name %> <%= @user.last_name %></h1>
</div>
<div class="container">
  <div class="col-6 offset-3">
    <ul class="nav nav-pills mb-4 mt-4" id="pills-tab" role="tablist">
      <li class="nav-item">
        <a class="nav-link active" id="pills-about-tab" data-toggle="pill" href="#pills-about" role="tab" aria-controls="pills-about" aria-selected="true">About me</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="pills-journey-tab" data-toggle="pill" href="#pills-journey" role="tab" aria-controls="pills-journey" aria-selected="false">Accompany journey</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="pills-reviews-tab" data-toggle="pill" href="#pills-reviews" role="tab" aria-controls="pills-reviews" aria-selected="false">All my reviews</a>
      </li>
    </ul>
  </div>


    <div class="tab-content" id="pills-tabContent">
      <div class="tab-pane fade show active" id="pills-about" role="tabpanel" aria-labelledby="pills-about-tab">
        <%= render 'about'%>
      </div>
      <div class="tab-pane fade" id="pills-journey" role="tabpanel" aria-labelledby="pills-journey-tab">
        <%= render 'journey'%>
      </div>
      <div class="tab-pane fade" id="pills-reviews" role="tabpanel" aria-labelledby="pills-reviews-tab">
        <%= render 'reviews'%>
      </div>
    </div>

</div>