config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get "dashboard", to: "dashboards#dashboard", as: 'dashboard'
  get 'profile/:id', to: 'pages#profile', as: :profile
  post 'bookings/:id/handle_booking', to: "bookings#handle_booking", as: :handle_booking
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :events do
    resources :bookings, only: [ :create, :destroy]
  end

  resources :users do
    resources :reviews, only: [ :create, :destroy ]
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def dashboard
    authorize :dashboard, :profile?
    @events = current_user.events
    @user = current_user
    @my_bookings = current_user.bookings
    @my_bookings_pending = current_user.bookings.where(approved: nil)
    @my_bookings_approved = current_user.bookings.where(approved: true)
    @requests = Booking.joins(:event).where(events: { user: current_user }, bookings: { approved: nil })
    @requests_approved = Booking.joins(:event).where(events: { user: current_user }, bookings: { approved: true })
    @approved = Booking.joins(:event).where(events: { user: current_user }, bookings: { approved: true })
  end
end

app/views/dashboards/_events-ahead.html.erb
  <h1 class="h1-profile">Find good company</h1>
  <div class="row">
    <% @requests_approved.each do |request| %>
      <div class="col-12 col-mb-6 col-lg-6 mb-4">
        <div class="card-event-request">
          <div class="d-flex">
             <%= cl_image_tag request.user.profile_image, class: "avatar-large mr-2" %>
            <div class="card-event-ahead-content">
              <p><span class="p-question">Who? </span><%= request.user.first_name %> <%= request.user.last_name %></p>
              <p><span class="p-question">Event? </span><%= request.event.name %></p>
              <p><span class="p-question">When? </span><%= request.event.date %></p>
              <p><span class="p-question">Contact Details? </span><%= request.user.email %></p>
            </div>
          </div>
          <div class="card-event-request-actions">
            <%= link_to profile_path(request.user) do %>
              <i class="fas fa-user-alt"></i>
            <% end %>
            <%= link_to profile_path(request.user) do %>
              <i class="fas fa-star mine"></i>
            <% end %>
            <%= link_to profile_path(request.user) do%>
              <i class="fa fa-pencil"></i>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>


  </div>
            <h1 class="h1-profile">Be good company</h1>
   <div class="row">
    <% @my_bookings_approved.each do |request| %>

      <div class="col-12 col-mb-6 col-lg-6 mb-4">
        <div class="card-event-company">
          <div class="d-flex">
             <%= cl_image_tag request.event.user.profile_image, class: "avatar-large mr-2" %>
            <div class="card-event-company-content">
              <p><span class="p-question">Who? </span><%= request.event.user.first_name %> <%= request.event.user.last_name %></p>
              <p><span class="p-question">Event? </span><%= request.event.name %></p>
              <p><span class="p-question">When? </span><%= request.event.date %></p>
              <p><span class="p-question">Contact Details? </span><%= request.event.user.email %></p>
            </div>
          </div>
          <div class="card-event-company-actions">
            <%= link_to profile_path(request.user) do %>
              <i class="fas fa-user-alt"></i>
            <% end %>
            <%= link_to profile_path(request.user) do %>
              <i class="fas fa-star mine"></i>
            <% end %>
             <%= link_to event_booking_path(request.event, request),
                method: :delete,
                data: { confirm: "Are you sure?" } do %>
                <i class="fa fa-trash-o"></i>
              <% end %>
          </div>
        </div>
      </div>
    <% end %>
       </div>

app/views/dashboards/_my-bookings.html.erb
  <div class="row">
    <% @my_bookings.each do |booking| %>
    <div class="col-6 col-mb-4 col-lg-4 mb-4">
      <%= link_to event_path(booking.event), id: 'card-clickable' do  %>
      <div class="profile-card">
        <% if booking.event.event_image.present? %>
        <div class="profile-card-image" style="background-image: url(<%= booking.event.event_image %>)"></div>
        <% else %>
        <div class="profile-card-image" style="background-image: url(<%=booking.event.event_category.default_image %>)"></div>
        <% end %>
        <div class="booking-card-content">
          <!-- if statement & checkbox image -->
          <div class="booking-card-title">
            <p class="category-tag">
              <%= booking.event.event_category.name %>
              <%= link_to event_booking_path(booking.event, booking),
                  method: :delete,
                  data: { confirm: "Are you sure?" } do %>
                  <i id="booking-actions" class="fa fa-trash-o"></i>
                <% end %>
            </p>
            <h4><%= booking.event.name %></h4>
            <p class="crop-description"><%= booking.event.event_description %></p>
          </div>
          <div class="profile-card-actions-status">
           <!--  <p>See more</p>
            <i class="fa fa-trash-o"></i> -->
            <% if booking.approved == true %>
            <i class="fas fa-glass-cheers" id="booking-status-icon"></i>
            <% elsif booking.approved == false %>
            <i class="far fa-frown" id="booking-status-icon"></i>
            <% elsif booking.approved == nil %>
            <i class="far fa-clock" id="booking-status-icon"></i>
            <% end %>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  <% end %>
  </div>

app/views/dashboards/_my-events.html.erb
  <div class="row">
    <% @events.each do |event| %>
    <div class="col-6 col-mb-4 col-lg-4 mb-4">
      <%= link_to event_path(event) do  %>
        <div class="profile-card">



          <% if event.event_image.file.present? %>
          <div class="profile-card-image" style="background-image: url(<%= event.event_image %>)"></div>
          <% else %>
          <div class="profile-card-image" style="background-image: url(<%=event.event_category.default_image %>)"></div>
          <% end %>
          <div class="profile-card-content">
            <!-- if statement & checkbox image -->
            <div class="profile-card-title">
              <p class="category-tag"><%= event.event_category.name %></p>
              <h4><%= event.name %></h4>
              <p class="crop-description"><%= event.event_description %></p>
            </div>
            <div class="profile-card-actions">
                <%= link_to 'See more', event_path(event)%>
                <%=link_to edit_event_path(event) do %>
                    <i class="fa fa-pencil"></i>
                <% end %>
                <%= link_to event_path(event),
                  method: :delete,
                  data: { confirm: "Are you sure?" } do %>
                  <i class="fa fa-trash-o"></i>
                <% end %></p>
            </div>
          </div>
        </div>
        <% end %>
    </div>
    <% end %>
  </div>

<!-- <button id="approve-request-sweet" class="btn btn-primary">Click me!</button> -->



    <% @requests.each do |request| %>
    <h1 class="h1-profile mb-4">See who wants to accompany you</h1>
  <div class="row">
    <div class="col-12 col-mb-6 col-lg-6 mb-4">
      <div class="card-event-request">
        <div class="d-flex">
            <%= cl_image_tag request.user.profile_image, class: "avatar-large mr-2" %>
            <div class="card-event-request-content">
              <p><span class="p-question">Who? </span><%= request.user.first_name %> <%= request.user.last_name %></p>
              <p><span class="p-question">Event? </span><%= request.event.name %></p>
              <p><span class="p-question">Motivation? </span><%= request.motivation %></p>
            </div>
          </div>
        <div class="card-event-request-actions">
          <%= link_to profile_path(request.user)do %>
          <i class="fas fa-user-alt"></i>
          <% end %>


          <%= button_to handle_booking_path(request, params: {approved: true}, :form => { :id => "approve-request-sweet"}) do %>
            <i id="approve-request-sweet" class="fas fa-heart"></i>
          <% end %>
          <%= button_to handle_booking_path(request, params: {approved: false}, :form => { :id => "decline-request-sweet"}, class: 'btn btn-request') do%>
          <i class="fas fa-times"></i>
          <% end %>
        </div>
      </div>
      </div>
    </div>
      <% end %>

app/views/dashboards/dashboard.html.erb
<div class="container">

  <!-- tabs for my events & my bookings -->
  <ul class="nav nav-pills mb-4 mt-4" id="pills-tab" role="tablist">
    <li class="nav-item">
      <a class="nav-link active" id="pills-events-tab" data-toggle="pill" href="#pills-events" role="tab" aria-controls="pills-events" aria-selected="true">Your Events</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" id="pills-bookings-tab" data-toggle="pill" href="#pills-bookings" role="tab" aria-controls="pills-bookings" aria-selected="false">Your Bookings</a>
    </li><li class="nav-item">
      <a class="nav-link" id="pills-ahead-tab" data-toggle="pill" href="#pills-ahead" role="tab" aria-controls="pills-ahead" aria-selected="false">Events ahead</a>
    </li>
  </ul>

  <div class="tab-content" id="pills-tabContent">
    <div class="tab-pane fade show active" id="pills-events" role="tabpanel" aria-labelledby="pills-events-tab">
      <%= render 'my-events'%>
    </div>
    <div class="tab-pane fade" id="pills-bookings" role="tabpanel" aria-labelledby="pills-bookings-tab">
      <%= render 'my-bookings'%>
    </div>
    <div class="tab-pane fade" id="pills-ahead" role="tabpanel" aria-labelledby="pills-ahead-tab">
      <%= render 'events-ahead'%>
    </div>
  </div>
</div>